import { ReferenceKind } from "@/models/reference/entities/reference-item.entity";

/**
 * English labels for the OCSC taxonomies.
 *
 * The source portal only ships Thai. These are ours, used for the EN UI; job content
 * itself (titles, agencies, requirements) is never translated — it stays in the language
 * the announcement was published in.
 *
 * Keys are the source's own integer ids, so the crawler can refresh `nameTh` from the live
 * endpoints without touching these.
 */
export const REFERENCE_EN: Record<ReferenceKind, Record<number, string>> = {
	[ReferenceKind.PROVINCE]: {
		1: "Krabi",
		2: "Bangkok",
		3: "Kanchanaburi",
		4: "Kalasin",
		5: "Kamphaeng Phet",
		6: "Khon Kaen",
		7: "Chanthaburi",
		8: "Chachoengsao",
		9: "Chon Buri",
		10: "Chai Nat",
		11: "Chaiyaphum",
		12: "Chumphon",
		13: "Chiang Rai",
		14: "Chiang Mai",
		15: "Trang",
		16: "Trat",
		17: "Tak",
		18: "Nakhon Nayok",
		19: "Nakhon Pathom",
		20: "Nakhon Phanom",
		21: "Nakhon Ratchasima",
		22: "Nakhon Si Thammarat",
		23: "Nakhon Sawan",
		24: "Nonthaburi",
		25: "Narathiwat",
		26: "Nan",
		27: "Bueng Kan",
		28: "Buri Ram",
		29: "Pathum Thani",
		30: "Prachuap Khiri Khan",
		31: "Prachin Buri",
		32: "Pattani",
		33: "Phra Nakhon Si Ayutthaya",
		34: "Phayao",
		35: "Phang Nga",
		36: "Phatthalung",
		37: "Phichit",
		38: "Phitsanulok",
		39: "Phetchaburi",
		40: "Phetchabun",
		41: "Phrae",
		42: "Phuket",
		43: "Maha Sarakham",
		44: "Mukdahan",
		45: "Mae Hong Son",
		46: "Yasothon",
		47: "Yala",
		48: "Roi Et",
		49: "Ranong",
		50: "Rayong",
		51: "Ratchaburi",
		52: "Lop Buri",
		53: "Lampang",
		54: "Lamphun",
		55: "Loei",
		56: "Si Sa Ket",
		57: "Sakon Nakhon",
		58: "Songkhla",
		59: "Satun",
		60: "Samut Prakan",
		61: "Samut Songkhram",
		62: "Samut Sakhon",
		63: "Sa Kaeo",
		64: "Saraburi",
		65: "Sing Buri",
		66: "Sukhothai",
		67: "Suphan Buri",
		68: "Surat Thani",
		69: "Surin",
		70: "Nong Khai",
		71: "Nong Bua Lam Phu",
		72: "Ang Thong",
		73: "Amnat Charoen",
		74: "Udon Thani",
		75: "Uttaradit",
		76: "Uthai Thani",
		77: "Ubon Ratchathani",
	},
	[ReferenceKind.EDUCATION_LEVEL]: {
		1: "Vocational Certificate",
		2: "Technical Certificate",
		3: "High Vocational Certificate",
		4: "Certificate",
		5: "Graduate Diploma",
		6: "Higher Graduate Diploma",
		7: "Associate Degree",
		8: "Bachelor's Degree",
		9: "Master's Degree",
		10: "Doctoral Degree",
		11: "Board Certification",
		99: "Other qualification",
	},
	[ReferenceKind.JOB_TYPE]: {
		0: "Unspecified",
		1: "General",
		2: "Academic / Knowledge Worker",
		3: "Directorial",
		4: "Executive",
		5: "Service",
		6: "Technical",
		7: "General Administration",
		8: "Specialised Profession",
		9: "Specific Expertise",
		10: "Advanced Expertise",
		99: "Other",
	},
	[ReferenceKind.JOB_CATEGORY]: {
		1: "Civil Servant",
		2: "Government Employee",
		99: "Other",
	},
	[ReferenceKind.JOB_LEVEL]: {
		0: "Unspecified",
		1: "Operational",
		2: "Experienced",
		3: "Senior",
		4: "Advanced Skill",
		5: "Practitioner",
		6: "Professional",
		7: "Senior Professional",
		8: "Expert",
		9: "Advisory",
		10: "Primary",
		11: "Higher",
		99: "Other",
	},
	[ReferenceKind.JOB_SELECTION]: {
		1: "Competitive Examination",
		2: "Selection",
		99: "Other",
	},
	[ReferenceKind.JOB_CONDITION]: {
		1: "No condition",
		2: "No transfers accepted",
		3: "Transfer at minimum salary step",
		99: "Other",
	},
};
